### ISSUE TITLE
The project app-id was changed

### ISSUE THREAD

**Issue by bilelmoussaoui** [flathub/org.gnome.GHex#2]
I have pushed a MR upstream to unify the app-id and make some stuff better. 
https://gitlab.gnome.org/GNOME/ghex/merge_requests/5

The new app-id (which was used elsewhere) is `org.gnome.GHex`. We might need to either update it here or end of life this package and create a new one.

**Comment by TingPing** [comment]
@ramcq 	Any updates on this being possible, should we just eol it?
