### ISSUE TITLE
texts are weird and wrong in flatpak version.

### ISSUE THREAD

**Issue by axzxc1236** [flathub/org.gnome.GHex#5]
I did a comparison of apt and flatpak version

apt version shows contents normally (but for some reason doesn't have language translation)

![](https://i.imgur.com/CHVUOZ6.png)

flatpak version (have language translation but text displays are all wrong, you can see I clicked on white background but actually selected texts)

![](https://i.imgur.com/dLf9PZf.png)

My distro is Pop! OS 20.04 and system language is Traditional Chinese/繁體中文, I don't know if these informations are enough.

**Comment by tinywrkb** [comment]
@axzxc1236 can you try again? I can't replicate with a recent build. I'm running with TW locale like this
```
flatpak run --env=LANG=zh_TW.UTF-8 --env=LC_MESSAGES=zh_TW.UTF-8 org.gnome.GHex
```
![swappy-20220404-144945](https://user-images.githubusercontent.com/44030034/161538372-6439b809-29bb-4e25-9289-fecedc19cfb5.png)

**Comment by larathbone** [comment]
Closing due to lack of followup. It's also unlikely this is still a live issue given it applied to 3.x.
